config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/trash_completed'
  get 'home/trash_all'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def trash_completed
        @trash_em = List.where(:completed => true).destroy_all
        redirect_to lists_url, notice: 'All Marked Items Were Successfully Deleted' 
    end

    def trash_all
        @trash_all = List.destroy_all
        redirect_to lists_url, notice: 'All Items Were Successfully Deleted' 
    end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @list = List.new
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <%= render 'lists/navbar' %>
  

   <div class = 'container'>
    <%= yield %>
   </div>


  </body>
</html>

app/views/lists/_check.html.erb
<%= form_with(model: @list, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

 

app/views/lists/_flash.html.erb
<br>
<% flash.each do |name, msg| %>
    <div>
        <button class = "close" data-dismiss="alert">
            <small><sup>X</sup></small>
        </button>
        <%= content_tag(:div, msg)%>
    </div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: @list, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :completed, class: 'form-check-input' %>
    <%= form.label :completed, class: 'form-check-label' %>
  </div>

  <div class="actions">
    <%= form.submit "Update", class: "btn btn-outline-secondary"%>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: @list, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline my-2 my-lg-0">
    <%= form.text_field :description, class: 'form-control mr-sm-2' %>
    <%= form.submit "Add Todo Item", class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "Todo List", root_path, class: 'navbar-brand' %>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
      </ul>
    </div>
    <div class = "justify-content-end">
        <%= render 'form_index', class:'justify-content-end'%>
    </div>
  </div>
</nav>

app/views/lists/_uncheck.html.erb
<%= form_with(model: @list, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

  

  

app/views/lists/edit.html.erb
</br>
<h1>Edit Todo Item</h1>
</br>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <%= render 'form'%>
  </div>
</div>

</br>
<% link_to 'Show', @list %> 
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<%= render 'flash', list: @list %>
<br>
<div class = 'text-center'>
  <table class = 'table'>
    <thead>
      <tr  class = 'row'>
        <th class = 'col col-lg-1'></th>
        <th class = 'col col-lg-8'>Description</th>
        <th class = 'col col-lg-3' colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @lists.each do |list| %>

      <% if list.completed %>
        <tr class = 'row'>
          <td class = 'col col-lg-1'>
            <%= form_for(list) do |form| %>
              <%= form.text_field :description, type: 'hidden'%>
              <%= form.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
              <%= form.submit "Undo"%>
            <%end%>
          </td>
          <td class = 'col col-lg-8 striker'><%= link_to list.description , edit_list_path(list) %><% list.description %></td>
          
          <td class = 'col col-lg-3'>
          <% link_to 'Show', list %>
          <% link_to 'Edit', edit_list_path(list) %>
          <% link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>

      <%else%>
      <tr class = 'row'>
          <td class = 'col col-lg-1'>
            <%= form_for(list) do |form| %>
                <%= form.text_field :description, type: 'hidden'%>
                <%= form.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
                <%= form.submit "Done"%>
              <%end%>
          </td>
          <td class = 'col col-lg-8'><%= link_to list.description , edit_list_path(list) %><% list.description %></td>
          
          <td class = 'col col-lg-3'>
          <% link_to 'Show', list %>
          <% link_to 'Edit', edit_list_path(list) %>
          <center><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %> </center>
          
          </td>
        </tr>

      <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%link_to 'Add Todo Item', new_list_path, class:'btn btn-secondary' %>

  <br/>
  <br/>

  <%= link_to 'Delete Completed Items', home_trash_completed_path, class: 'btn btn-outline-secondary', data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Delete All Items', home_trash_all_path, class: 'btn btn-outline-secondary', data: { confirm: 'Are you sure?' }%>
  </div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Todo Item:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>